-- 받은 메세지 지우기
ALTER TABLE MESSAGE
ADD MESSAGE_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL;

-- 보낸 메세지 지우기
ALTER TABLE MESSAGE
ADD MESSAGE_SEND_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL;

-- 메세지 지우는게 없어서 추가

-- 받은 메세지 함 
SELECT m.MESSAGE_NO, m.MESSAGE_CONTENT, m.SEND_DATE, m.SEND_MEMBER, m.RECEIVED_MEMBER, 
		PROFILE_IMG, MEMBER_NICKNAME, m.MESSAGE_DEL_FL,
		<![CDATA[
		CASE  
			WHEN SYSDATE - m.SEND_DATE < 1/24/60
			THEN FLOOR( (SYSDATE - m.SEND_DATE) * 24 * 60 * 60 ) || '초 전'
			WHEN SYSDATE - m.SEND_DATE < 1/24
			THEN FLOOR( (SYSDATE - m.SEND_DATE) * 24 * 60) || '분 전'
			WHEN SYSDATE - m.SEND_DATE < 1
			THEN FLOOR( (SYSDATE - m.SEND_DATE) * 24) || '시간 전'
			ELSE TO_CHAR(m.SEND_DATE, 'YYYY-MM-DD')
		END CREATE_DATE
		]]>
FROM MESSAGE m
JOIN "MEMBER_PROFILE" ON (SEND_MEMBER=MEMBER_NO)
JOIN "MEMBER" USING (MEMBER_NO)
WHERE RECEIVED_MEMBER = 2
AND m.MESSAGE_DEL_FL ='N'
;

COMMIT;
-- 보낸 메세지 함 
SELECT m.MESSAGE_NO, m.MESSAGE_CONTENT, 
	   TO_CHAR(m.SEND_DATE, 'YY"년" MM"월" DD"일" HH24":"MI') SEND_DATE, 
	   m.SEND_MEMBER, m.RECEIVED_MEMBER,
       MP.PROFILE_IMG, R.MEMBER_NICKNAME MEMBER_NICKNAME, m.MESSAGE_SEND_DEL_FL
FROM MESSAGE m
JOIN "MEMBER_PROFILE" MP ON (m.RECEIVED_MEMBER = MP.MEMBER_NO)
JOIN "MEMBER" S ON (m.SEND_MEMBER = S.MEMBER_NO)
JOIN "MEMBER" R ON (m.RECEIVED_MEMBER = R.MEMBER_NO)
WHERE m.SEND_MEMBER = 3
AND m.MESSAGE_SEND_DEL_FL = 'N'
ORDER BY 1 DESC
;


-- 메세지 조회
SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER, MESSAGE_DEL_FL, MESSAGE_SEND_DEL_FL
FROM MESSAGE;


-- 프로필 조회
SELECT MEMBER_NO, PROFILE_IMG, BACKGROUND_IMG, MEMBER_INFO, MEMBER_CAREER, MEMBER_TECH, CERTIFICATE_NO
FROM MEMBER_PROFILE;

-- 멤버 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY
FROM "MEMBER";


COMMIT;
-- 메세지 삽입
INSERT INTO MESSAGE
(MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER)
VALUES(SEQ_MESSAGE_NO.NEXTVAL, '테스트 메세지1', SYSDATE, 2, 3)
;

-- 받은 메세지 삭제(삭제를 가장한 업데이트)
UPDATE MESSAGE
SET MESSAGE_DEL_FL='Y' 
WHERE MESSAGE_NO=1
AND MESSAGE_DEL_FL='N'
;
-- 보낸 메세지 삭제(삭제를 가장한 업데이트)
UPDATE MESSAGE
SET MESSAGE_DEL_FL='Y' 
WHERE MESSAGE_NO=1
AND MESSAGE_SEND_DEL_FL='N'
;

-- 살리기
UPDATE MESSAGE
SET MESSAGE_DEL_FL='N' 
WHERE MESSAGE_NO=1
AND MESSAGE_DEL_FL='Y'
;




SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY
FROM "MEMBER";

INSERT INTO "MEMBER"
(MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY)
VALUES(2, 'lnh@ping.com', '123', '나봉', 'nabong', SYSDATE	, 'N'	, 1	);

INSERT INTO "MEMBER"
(MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY)
VALUES(3, 'test@ping.com', '123', '호나', 'hona', SYSDATE	, 'N'	, 1	);

-- 메세지 프로필
INSERT INTO MEMBER_PROFILE
(MEMBER_NO, PROFILE_IMG, BACKGROUND_IMG, MEMBER_INFO, MEMBER_CAREER, MEMBER_TECH, CERTIFICATE_NO)
VALUES(3, '/resources/images/pingpong.ico', '/resources/images/mypage/20230516174653_33272.png', '한줄 소개 입니다.', '소개입니다.', NULL , NULL);

UPDATE MEMBER_PROFILE
SET PROFILE_IMG='/resources/images/mypage/hamsterart.jpg'
WHERE MEMBER_NO=3;

