-- 받은 메세지 함 
SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER, PROFILE_IMG, MEMBER_NICKNAME
FROM MESSAGE
JOIN "MEMBER_PROFILE" ON (SEND_MEMBER=MEMBER_NO)
JOIN "MEMBER" USING (MEMBER_NO)
WHERE RECEIVED_MEMBER = 2
;

-- 
ALTER TABLE MEMBER_PROFILE
ADD MESSAGE_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL;
-- 메세지 지우는게 없어서 

SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER, PROFILE_IMG, MEMBER_NICKNAME,
	<![CDATA[
	CASE  
		WHEN SYSDATE - SEND_DATE < 1/24/60
		THEN FLOOR( (SYSDATE - SEND_DATE) * 24 * 60 * 60 ) || '초 전'
		WHEN SYSDATE - SEND_DATE < 1/24
		THEN FLOOR( (SYSDATE - SEND_DATE) * 24 * 60) || '분 전'
		WHEN SYSDATE - SEND_DATE < 1
		THEN FLOOR( (SYSDATE - SEND_DATE) * 24) || '시간 전'
		ELSE TO_CHAR(SEND_DATE, 'YYYY-MM-DD')
	END CREATE_DATE
	]]>
FROM MESSAGE
JOIN "MEMBER_PROFILE" ON (SEND_MEMBER=MEMBER_NO)
JOIN "MEMBER" USING (MEMBER_NO)
WHERE RECEIVED_MEMBER = #{memberNo}
;

-- 보낸 메세지 함 
SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER, PROFILE_IMG, MEMBER_NICKNAME
FROM MESSAGE
JOIN "MEMBER_PROFILE" ON (SEND_MEMBER=MEMBER_NO)
JOIN "MEMBER" USING (MEMBER_NO)
WHERE SEND_MEMBER = 2
;
SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER, PROFILE_IMG, MEMBER_NICKNAME
FROM MESSAGE
JOIN "MEMBER_PROFILE" ON (SEND_MEMBER=MEMBER_NO)
JOIN "MEMBER" USING (MEMBER_NO)
WHERE SEND_MEMBER = 2
;


-- 메세지 조회
SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER
FROM MESSAGE;

-- 프로필 조회
SELECT MEMBER_NO, PROFILE_IMG, BACKGROUND_IMG, MEMBER_INFO, MEMBER_CAREER, MEMBER_TECH, CERTIFICATE_NO
FROM MEMBER_PROFILE;

-- 멤버 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY
FROM "MEMBER";


COMMIT;
-- 메세지 삽입
INSERT INTO MESSAGE
(MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER)
VALUES(SEQ_MESSAGE_NO.NEXTVAL, '테스트 메세지', SYSDATE	, 2, 3)
;



SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY
FROM "MEMBER";

INSERT INTO "MEMBER"
(MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY)
VALUES(2, 'lnh@ping.com', '123', '나봉', 'nabong', SYSDATE	, 'N'	, 1	);

INSERT INTO "MEMBER"
(MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY)
VALUES(3, 'test@ping.com', '123', '호나', 'hona', SYSDATE	, 'N'	, 1	);

-- 메세지 프로필
INSERT INTO MEMBER_PROFILE
(MEMBER_NO, PROFILE_IMG, BACKGROUND_IMG, MEMBER_INFO, MEMBER_CAREER, MEMBER_TECH, CERTIFICATE_NO)
VALUES(2, '/resources/images/pingpong.ico', '/resources/images/mypage/20230516174653_33272.png', '한줄 소개 입니다.', '소개입니다.', NULL , NULL);
