-- 
ALTER TABLE MESSAGE
ADD MESSAGE_DEL_FL CHAR(1) DEFAULT 'N' NOT NULL;
-- 메세지 지우는게 없어서 추가

-- 받은 메세지 함 
SELECT m.MESSAGE_NO, m.MESSAGE_CONTENT, m.SEND_DATE, m.SEND_MEMBER, m.RECEIVED_MEMBER, 
		PROFILE_IMG, MEMBER_NICKNAME, m.MESSAGE_DEL_FL,
		<![CDATA[
		CASE  
			WHEN SYSDATE - m.SEND_DATE < 1/24/60
			THEN FLOOR( (SYSDATE - m.SEND_DATE) * 24 * 60 * 60 ) || '초 전'
			WHEN SYSDATE - m.SEND_DATE < 1/24
			THEN FLOOR( (SYSDATE - m.SEND_DATE) * 24 * 60) || '분 전'
			WHEN SYSDATE - m.SEND_DATE < 1
			THEN FLOOR( (SYSDATE - m.SEND_DATE) * 24) || '시간 전'
			ELSE TO_CHAR(m.SEND_DATE, 'YYYY-MM-DD')
		END CREATE_DATE
		]]>
FROM MESSAGE m
JOIN "MEMBER_PROFILE" ON (SEND_MEMBER=MEMBER_NO)
JOIN "MEMBER" USING (MEMBER_NO)
WHERE RECEIVED_MEMBER = 2
AND m.MESSAGE_DEL_FL ='N'
;

COMMIT;
-- 보낸 메세지 함 
SELECT m.MESSAGE_NO, m.MESSAGE_CONTENT, 
	   TO_CHAR(m.SEND_DATE, 'YY"년" MM"월" DD"일" HH24":"MI') SEND_DATE, 
	   m.SEND_MEMBER, m.RECEIVED_MEMBER,
       MP.PROFILE_IMG, R.MEMBER_NICKNAME MEMBER_NICKNAME, m.MESSAGE_SEND_DEL_FL
FROM MESSAGE m
JOIN "MEMBER_PROFILE" MP ON (m.RECEIVED_MEMBER = MP.MEMBER_NO)
JOIN "MEMBER" S ON (m.SEND_MEMBER = S.MEMBER_NO)
JOIN "MEMBER" R ON (m.RECEIVED_MEMBER = R.MEMBER_NO)
WHERE m.SEND_MEMBER = 2
AND m.MESSAGE_SEND_DEL_FL = 'N';
ORDER BY m.MESSAGE_NO DESC;


-- 메세지 조회
SELECT MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER, MESSAGE_DEL_FL
FROM MESSAGE;


-- 프로필 조회
SELECT MEMBER_NO, PROFILE_IMG, BACKGROUND_IMG, MEMBER_INFO, MEMBER_CAREER, MEMBER_TECH, CERTIFICATE_NO
FROM MEMBER_PROFILE;

-- 멤버 조회
SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY
FROM "MEMBER";

		INSERT INTO MESSAGE
		(MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER)
		VALUES(SEQ_MESSAGE_NO.NEXTVAL, '테스트', SYSDATE, 3, 2)
		;
COMMIT;
-- 메세지 삽입
INSERT INTO MESSAGE
(MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER)
VALUES(SEQ_MESSAGE_NO.NEXTVAL, '안녕~난 호나쓰~', SYSDATE, 3, 1)
;
-- 메세지 삽입
INSERT INTO MESSAGE
(MESSAGE_NO, MESSAGE_CONTENT, SEND_DATE, SEND_MEMBER, RECEIVED_MEMBER)
VALUES(SEQ_MESSAGE_NO.NEXTVAL, '햄스터 정모 제발 부탁드려요....프로필 사진 개인적으로 써도 될까요?', SYSDATE, 1, 2)
;



SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY
FROM "MEMBER";

INSERT INTO "MEMBER"
(MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY)
VALUES(2, 'lnh@ping.com', '123', '나봉', 'nabong', SYSDATE	, 'N'	, 1	);

INSERT INTO "MEMBER"
(MEMBER_NO, MEMBER_EMAIL, MEMBER_PW, MEMBER_NICKNAME, MEMBER_URL, ENROLL_DATE, MEMBER_DEL_FL, AUTHORITY)
VALUES(3, 'test@ping.com', '123', '호나', 'hona', SYSDATE	, 'N'	, 1	);

-- 메세지 프로필
INSERT INTO MEMBER_PROFILE
(MEMBER_NO, PROFILE_IMG, BACKGROUND_IMG, MEMBER_INFO, MEMBER_CAREER, MEMBER_TECH, CERTIFICATE_NO)
VALUES(3, '/resources/images/pingpong.ico', '/resources/images/mypage/20230516174653_33272.png', '한줄 소개 입니다.', '소개입니다.', NULL , NULL);

UPDATE MEMBER_PROFILE
SET PROFILE_IMG='/resources/images/mypage/hamsterart.jpg'
WHERE MEMBER_NO=3;

SELECT * FROM MESSAGE;





-----------------------
-- 알람 ----

CREATE TABLE "NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_COMENT"	VARCHAR2(1000)		NOT NULL,
	"ELAPSED_TIME"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MEMBER_NO"	NUMBER		NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS '알림 번호(SEQ_NOTICE_NO)';

COMMENT ON COLUMN "NOTICE"."NOTICE_COMENT" IS '알림 내용';

COMMENT ON COLUMN "NOTICE"."ELAPSED_TIME" IS '받은 시간';

COMMENT ON COLUMN "NOTICE"."MEMBER_NO" IS '회원번호';

DROP TABLE "NOTICE";


----------
CREATE SEQUENCE SEQ_NOTICE_NO NOCACHE;


SELECT NOTICE_NO, NOTICE_COMENT, ELAPSED_TIME, MEMBER_NO,
	   MEMBER_NICKNAME 
FROM NOTICE
JOIN "MEMBER" USING (MEMBER_NO)
WHERE MEMBER_NO = 2
;

-- 알람 삽입
INSERT INTO NOTICE
(NOTICE_NO, NOTICE_COMENT, ELAPSED_TIME, MEMBER_NO)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '테스트 알림3', SYSDATE, 2)
;


SELECT PROFILE_IMG
FROM MEMBER_PROFILE
WHERE MEMBER_NO =
;
-- 알람 받은 사람 번호 찾기
SELECT MEMBER_NO 
FROM BOARD
WHERE BOARD_NO  
;
SELECT NOTICE_NO, NOTICE_COMENT, ELAPSED_TIME, MEMBER_NO
FROM NOTICE
ORDER BY 1 DESC
;
INSERT INTO NOTICE
(NOTICE_NO, NOTICE_COMENT, ELAPSED_TIME, MEMBER_NO)
VALUES(SEQ_NOTICE_NO.NEXTVAL, '알람', SYSDATE	, 2)
;

-- 팔로우 확인
SELECT FOLLOW_NO, MEMBER_NO, FOLLOWER_NO
FROM FOLLOW
;


-- MEMBER_NO 팔로우 당한 사람 / FOLLOWER_NO 팔로우 한 사람
INSERT INTO FOLLOW
(FOLLOW_NO, MEMBER_NO, FOLLOWER_NO)
VALUES(SEQ_FOLLOW_NO.NEXTVAL, 3, 2)
;

-- 팔로우 여
SELECT COUNT(*) 
FROM FOLLOW
WHERE MEMBER_NO =2
AND FOLLOWER_NO =3
;

DELETE FROM FOLLOW
WHERE MEMBER_NO =2
AND FOLLOWER_NO =1
;

-- 내가 팔로우 하는 사람들
-- MEMBER_NO 팔로우 당한 사람 / FOLLOWER_NO 팔로우 한 사람 -> MEMBER_NICKNAME
SELECT MEMBER_NO, FOLLOWER_NO, MEMBER_NICKNAME 
FROM FOLLOW
JOIN "MEMBER" USING (MEMBER_NO)
WHERE FOLLOWER_NO =2
ORDER BY FOLLOW_NO
;

-- 나를 팔로우 하는 사람들

SELECT F.MEMBER_NO, F.FOLLOWER_NO, M2.MEMBER_NICKNAME AS FOLLOWER_NICKNAME
FROM FOLLOW F
JOIN "MEMBER" M1 ON F.MEMBER_NO = M1.MEMBER_NO
JOIN "MEMBER" M2 ON F.FOLLOWER_NO = M2.MEMBER_NO
WHERE F.MEMBER_NO = 2
ORDER BY F.FOLLOW_NO
;

-- 메인 페이지 게시글 최신순
SELECT BOARD_NO, IMG_ADDRESS THUMBNAIL, MEMBER_NO
FROM BOARD
JOIN BOARD_IMG USING(BOARD_NO)
WHERE BOARD_DEL_FL = 'N'
AND IMG_ORDER = 1
ORDER BY BOARD_NO DESC
;

-- 메인 페이지 게시글 최신순
SELECT BOARD_NO, IMG_ADDRESS THUMBNAIL, MEMBER_NO
FROM BOARD
JOIN BOARD_IMG USING(BOARD_NO)
WHERE BOARD_DEL_FL = 'N'
AND IMG_ORDER = 1
ORDER BY BOARD_NO DESC
;

-- 메인 슬라이드 좋아요
SELECT BOARD_NO, IMG_ADDRESS THUMBNAIL, MEMBER_NO, 
		(SELECT COUNT(*) FROM "LIKE"
		GROUP BY BOARD_NO
		ORDER BY 1 DESC) AS "LIKE_COUNT"
FROM BOARD
JOIN BOARD_IMG USING(BOARD_NO)
JOIN LIKE USING(BOARD_NO)
WHERE BOARD_DEL_FL = 'N'
AND IMG_ORDER = 1
ORDER BY BOARD_NO DESC
;

-- 좋아요수 카운트
SELECT COUNT(*) FROM "LIKE"
GROUP BY BOARD_NO
ORDER BY 1 DESC
;



SELECT B.BOARD_NO, BI.IMG_ADDRESS AS THUMBNAIL, B.MEMBER_NO,
  (SELECT COUNT(*)
   FROM "LIKE"
   WHERE "LIKE".BOARD_NO = B.BOARD_NO
   ) AS LIKE_COUNT
FROM BOARD B
JOIN BOARD_IMG BI ON B.BOARD_NO = BI.BOARD_NO
WHERE B.BOARD_DEL_FL = 'N'
AND BI.IMG_ORDER = 1
ORDER BY LIKE_COUNT DESC
FETCH FIRST 10 ROWS ONLY
;

